"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.routerQualidade = void 0;
const express_1 = require("express");
const QualidadeController_1 = require("../controllers/QualidadeController");
const ensuredUser_1 = require("../middleware/ensuredUser");
const routerQualidade = (0, express_1.Router)();
exports.routerQualidade = routerQualidade;
const Qualidade = new QualidadeController_1.QualidadeController();
routerQualidade.get('/', ensuredUser_1.ensuredUser, Qualidade.ListAll);
routerQualidade.get('/:id', ensuredUser_1.ensuredUser, Qualidade.FindByQualidade);
routerQualidade.put('/', ensuredUser_1.ensuredUser, Qualidade.UpdateQualidade);
routerQualidade.post('/', ensuredUser_1.ensuredUser, Qualidade.CreateQualidade);
routerQualidade.delete('/:id', ensuredUser_1.ensuredUser, Qualidade.DeleteQualidade);
