"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv/config");
const express_1 = __importDefault(require("express"));
require("reflect-metadata");
const cors_1 = __importDefault(require("cors"));
const userRoutes_1 = require("./Routes/userRoutes");
require("./database");
const tipeRoutes_1 = require("./Routes/tipeRoutes");
const aparenciaRouter_1 = require("./Routes/aparenciaRouter");
const qualidadeRouter_1 = require("./Routes/qualidadeRouter");
const objetivo_1 = require("./Routes/objetivo");
const pacoteRouter_1 = require("./Routes/pacoteRouter");
const UserActiveRouter_1 = require("./Routes/UserActiveRouter");
const server = (0, express_1.default)();
server.use((0, cors_1.default)());
server.use(express_1.default.json());
server.use(express_1.default.urlencoded({ extended: true }));
server.use('/user', userRoutes_1.routerUser);
server.use('/type', tipeRoutes_1.routerType);
server.use('/aparencia', aparenciaRouter_1.routerAparencia);
server.use('/qualidade', qualidadeRouter_1.routerQualidade);
server.use('/objetivo', objetivo_1.routerObjetivo);
server.use('/pacote', pacoteRouter_1.routerPacote);
server.use('/ActiveUser', UserActiveRouter_1.routesUserActive);
const port = process.env.PORT || 3001;
server.listen(port, () => console.log("Servidor rodando na porta 3001"));
